version: '3.5'

services:
  api:
    container_name: koa-app-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/env/development
      - src/env/development.secret
    ports:
      - 4000:4000
    depends_on:
      - mysql
    volumes:
      - ".:/usr/app"

  mysql:
    image: mysql:5.7
    container_name: koa-app-sql
    env_file:
      - src/env/development
      - src/env/development.secret
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

