version: '3.5'

services:
  api:
    container_name: koa-app-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/env/development
      - src/env/development.secret
    ports:
      - 4000:4000
    depends_on:
      - mysql
    volumes:
      - "./src:/usr/app/src"
      - "./logs:/usr/app/logs"
      - "./database:/usr/app/database"

  mysql:
    image: mysql:5.7.22
    container_name: koa-app-sql
    env_file:
      - src/env/development
      - src/env/development.secret
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

