version: '3.5'

services:
  api:
    container_name: koa-app-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/env/development
      - src/env/development.secret
    ports:
      - 4000:4000
    depends_on:
      - mariadb
    volumes:
      - "./src:/usr/app/src"
      - "./logs:/usr/app/logs"
      - "./database:/usr/app/database"
    entrypoint:
      - ./entrypoint.sh
      - ./node_modules/.bin/nodemon
      - ./bin/server

  mariadb:
    image: mariadb/server:10.3.13
    container_name: koa-app-mariadb
    env_file:
      - src/env/development
      - src/env/development.secret
    ports:
      - 3307:3306
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:

